require("plugins")

require("core.options")
require("core.statusline")
require("core.keymaps")
require("core.autocmds")

require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.blink")
require("plugins.fzf")
require("plugins.mini")
require("plugins.treesitter")
require("plugins.gitsigns")
require("plugins.lsp")
require("plugins.blink")
require("plugins.bufferline")
